### ISSUE TITLE
[Bug] Reigns dont work

### ISSUE THREAD

**Issue by loonietick** [OrbisMC-Dev/Issue-Tracker#2]
### Reigns dont work.
I have a reign and a horse.
The horse goes 8.39 meters per second without
I use the reign and it doesnt go any faster
it stays at 8.39 meters per sec using reign.
please fix

**Comment by InjurynSickness** [comment]
I'm pretty sure it works because it just uses a speed effect it doesn't change the horse attributes whatsoever

**Comment by loonietick** [comment]
> I'm pretty sure it works because it just uses a speed effect it doesn't change the horse attributes whatsoever

I tried to use multiple horses and it doesnt work. 
Is it actually applying the speed effect?

**Comment by InjurynSickness** [comment]
Send a video

**Comment by loonietick** [comment]
Without reign:
https://github.com/user-attachments/assets/b72a70e1-fe5c-4a76-aaf5-acd758815d72

With reign:

https://github.com/user-attachments/assets/c502eef9-bc41-4a5c-9034-d2acfdea41a1

if you look at top left the speed doesn't change

**Comment by InjurynSickness** [comment]
Issue has been fixed
